[workspace]
resolver = "3"
members = [
    "dawn-bindgen",
    "dawn-sys",
    "dawn-macros",
    "dawn-rs",
]

[workspace.package]
authors = ["Nekomaru <Nekomaru@pku.edu.cn>"]
repository = "https://github.com/Nekomaru-PKU/dawn-rs"
